name: Run tests and linters
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Nox with pip
      run: pip install nox==2022.1.7
    - name: Install Poetry with pip
      run: pip install poetry==1.1.13
    - name: Lint and test with Nox
      run: nox
